   name: Run Pre-commit Hooks

   on:
     pull_request:
       branches:
         - main
     push:
       branches:
         - main

   jobs:
     pre-commit:
       runs-on: [self-hosted]  # Используйте ваш локальный self-hosted раннер

       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Run Ubuntu container
           run: |
             docker run --rm -v ${{ github.workspace }}:/app -w /app ubuntu:20.04 bash -c "
             apt-get update &&
             apt-get install -y python3 python3-pip python3-venv git curl &&
             python3 -m venv venv &&
             . venv/bin/activate &&
             pip install --upgrade pip &&
             pip install -r requirements.txt &&
             
             git fetch origin main &&
             files=\$(git diff --name-only origin/main) &&
             if [ -n \"\$files\" ]; then
               pre-commit run --files \$files;
             else
               echo 'No modified files to check.';
             fi
             "